apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: tomcat-namespace
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32227
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace: tomcat-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat-container
          image: tomcat:9-jre17
          ports:
            - containerPort: 8080
          env:
          - name: TOMCAT_USERNAME
            value: admin
          - name: TOMCAT_PASSWORD
            value: password123
